config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about", as: "about"
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :items
    #itemsに対してreviewsをネストしないのはレビュー一覧で全てのレビュー情報を表示するため
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews do
      resources :review_comments
    end
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :genres
    get "item/confirm/:id" => "items#confirm", as: "item/confirm"
    resources :items
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts
    resources :post_comments
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews
    resources :review_comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :review, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, length: { in: 1..50 }
  validates :introduction, presence: true, length: { in: 1..255 }
  validates :price, presence: true, numericality: {only_integer: true}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def index
    @items = Item.all.order('updated_at DESC')
  end

  def show
    @item = Item.find(params[:id])
    @reviews = Review.where(item_id: @item.id).order('updated_at DESC')
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  def confirm
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_item_index_card.html.erb
<div class="card">
  <div class="img-siz">
    <%= image_tag item.get_image(300, 300), class:"img-fit" %>
  </div>

  <div class="card-body">
    <h6 class="card-title omit">
      <%= item.name %>
    </h6>

    <p class="card-text">
      <%= item.price %>円<br />
      レビュー数：<%= item.review.count %>
    </p>
  </div>
</div>

app/views/admin/items/_item_show_card.html.erb
<div class="card">
  <%= image_tag item.get_image(200, 200), class:"card-img-top" %>
  <div class="p-2">
    <p><%= item.name %></p>
    <p>価格：<%= item.price %>円</p>
    <p><%= item.introduction %></p>
  </div>
</div>

app/views/admin/items/confirm.html.erb
<h2 class="row justify-content-center text-danger mt-3">
  <strong>商品削除確認</strong>
</h2>

<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-12 text-center mb-3">
    <%= image_tag @item.get_image(300, 300) %>
  </div>

  <div class="col-lg-8 col-md-8 col-sm-12">
    <h4 class="text-center">
      商品名：<%= @item.name %>
    </h4>

    <h5 class="text-center">
      価格：<%= @item.price %>円
    </h5>

    <h5 class="text-center">
      紹介文
    </h5>

    <div class="p-2">
      <p class="text-center">
        <%= @item.introduction %>
      </p>
    </div>

    <h5 class="col text-center mt-3">
      レビュー件数：<%= @item.review.count %>
    </h5>
  </div>
</div>

<p class="row justify-content-center text-center mt-5">
  <strong>
    この商品に関する情報が完全に消去されます<br />
    本当に削除してもよろしいですか？
  </strong>
</p>

<div class="row justify-content-center mt-4">
  <%= link_to "削除する", admin_item_path(@item.id), method: :delete, class:"btn btn-outline-danger" %>
</div>

app/views/admin/items/edit.html.erb
<h2 class="mt-3">商品編集</h2>

<%= form_with model: @item, url: admin_item_path, method: :patch, class:"mt-3" do |f| %>
  <div class="row form-group col-lg-8">
    <%= f.label :image, "商品画像", class:"mr-2" %>
    <%= f.file_field :image, accept: "image/*", required: true %>
  </div>

  <div class="row form-group col-lg-8 col-md-11 col-sm-12">
    <%= f.label :name, "商品名", class:"mr-4" %>
    <%= f.text_field :name, required: true, class:"col-4 form-control" %>
  </div>

  <div class="row form-group col-lg-8 col-md-10 col-sm-10">
    <%= f.label :introduction, "商品説明", class:"mr-2" %>
    <%= f.text_area :introduction, required: true, class:"col form-control" %>
  </div>

  <div class="row form-group col-lg-8 col-md-10 col-sm-10">
    <%= f.label :price, "販売価格", class:"mr-2" %>
    <%= f.text_field :price, required: true, class:"col-2 form-control" %>円
  </div>

  <div class="row justify-content-center">
    <%= f.submit '編集完了', class:"btn btn-success col-2" %>
  </div>
<% end %>

app/views/admin/items/index.html.erb
<div class="row">
  <h2 class="col-lg-8 col-md-8 col-sm-8 mt-3">商品一覧</h2>

  <h4 class="col-lg-4 col-md-4 col-sm-4 mt-3">
    <%= link_to "商品登録", new_admin_item_path, class:"btn btn-success" %>
  </h4>

  <% if @items.count >= 1 %>
    <% @items.each do |item| %>
      <div class="col-lg-2 col-md-3 col-sm-4 mt-3">
        <%= link_to admin_item_path(item.id) do %>
          <%= render 'admin/items/item_index_card', item: item %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h5 class="text-center mt-4">
      商品が登録されていません<br />
      上の<strong>商品登録</strong>ボタンをクリックして<br />
      必要事項を入力し 商品登録してください
    </h5>
  <% end %>
</div>

app/views/admin/items/new.html.erb
<h2 class="mt-3">商品登録</h2>

<%= form_with model: @item, url: admin_items_path, class:"mt-3" do |f| %>
  <div class="row form-group col-lg-8 col-md-10 col-sm-10">
    <%= f.label :image, "商品画像", class:"mr-2" %>
    <%= f.file_field :image, accept: "image/*", required: true %>
  </div>

  <div class="row form-group col-lg-8 col-md-11 col-sm-12">
    <%= f.label :name, "商品名", class:"mr-4" %>
    <%= f.text_field :name, required: true, class:"col-4 form-control" %>
  </div>

  <div class="row form-group col-lg-8 col-md-10 col-sm-10">
    <%= f.label :introduction, "商品説明", class:"mr-2" %>
    <%= f.text_area :introduction, required: true, class:"col form-control" %>
  </div>

  <div class="row form-group col-lg-8 col-md-10 col-sm-10">
    <%= f.label :price, "販売価格", class:"mr-2" %>
    <%= f.text_field :price, required: true, class:"col-2 form-control" %>円
  </div>

  <div class="row justify-content-center">
    <%= f.submit '商品登録', class:"btn btn-success col-2" %>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<h2 class="mt-3">商品詳細</h2>

<div class="row mt-3">
  <div class="col-lg-5 col-md-5 col-sm-12">
    <%= render 'item_show_card', item: @item %>

    <div class="col mt-3 mb-3 text-center">
      <%= link_to "商品編集", edit_admin_item_path(@item.id), class:"mr-2 btn btn-primary" %>

      <%= link_to "商品削除", admin_item_confirm_path(@item.id), class:"btn btn-danger" %>
    </div>
  </div>

  <div class="col-lg-7 col-md-7 col-sm-12">
    <% if @item.review.count >= 1 %>
      <h5 class="text-center">この商品のレビュー</h5>

      <% @reviews.each do |review| %>
        <div class="row mt-2 border border-secondary rounded p-3">
          <div class="col-lg-6 col-md-12 col-sm-12">
            <%= link_to admin_review_path(review.id), class:"text-dark" do %>
              <strong><%= review.title %></strong>
            <% end %>
          </div>

          <div class="row col-lg-6 col-md-12 col-sm-12 justify-content-end">
            <%= render 'admin/reviews/star', review: review %>
          </div>

          <%= link_to admin_customer_path(review.customer_id) do %>
            <p class="col-lg-12 col-md-12 col-sm-12 mt-2">
              投稿者
              <%= review.customer.nickname %>
            </p>
          <% end %>

          <div class="col-lg-12 col-md-12 col-sm-12 mt-3">
            <%= review.text %>
          </div>
        </div>

        <p class="col-lg-12 col-md-12 col-sm-12 mt-2 text-right">
          投稿日時
          <%= review.updated_at.strftime("%Y_%m/%d_%H:%M") %>
        </p>
      <% end %>
    <% else %>
      <h5 class="text-center">この商品はまだレビューがありません</h5>
    <% end %>
  </div>
</div>