config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about", as: "about"
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :items
    #itemsに対してreviewsをネストしないのはレビュー一覧で全てのレビュー情報を表示するため
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews do
      resources :review_comments
    end
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :genres
    get "item/confirm/:id" => "items#confirm", as: "item/confirm"
    resources :items
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts
    resources :post_comments
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews
    resources :review_comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :last_name, presence: true, length: { in: 1..50 }
  validates :first_name, presence: true, length: { in: 1..50 }
  validates :last_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :first_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :nickname, presence: true, length: { in: 1..15 }
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120, message: "は0から120までが登録できます" }

  def self.guest
    find_or_create_by!(nickname: 'ゲスト会員' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.first_name = 'ゲスト'
      customer.first_name_kana = '会員'
      customer.last_name = 'ゲスト'
      customer.last_name_kana = 'カイイン'
      customer.nickname = 'ゲスト会員'
      customer.phone_number = 00012344321
      customer.age = 20
      customer.is_deleted = false
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.order('created_at DESC')
  end

  def show
    @customer = Customer.find(params[:id])
    @reviews = Review.where(customer_id: @customer.id).order('updated_at DESC').limit(1)
    @posts = Post.where(customer_id: @customer.id).order('created_at DESC').limit(1)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  def review
    @customer = Customer.find(params[:id])
    @reviews = Review.where(customer_id: @customer.id).order('updated_at DESC')
  end

  def post
    @customer = Customer.find(params[:id])
    @posts = Post.where(customer_id: @customer.id).order('created_at DESC')
  end

  private

  def customer_params
    params.require(:customer).permit(:is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_show.html.erb
<div class="row mt-3">
  <p class="col-lg-4 col-md-6 col-sm-4 text-right">名前</p>
  <p class="col-lg-1 col-md-1 col-sm-1">：</p>
  <p class="col-lg-7 col-md-12 col-sm-7">
    <%= customer.last_name %>
    <%= " " %>
    <%= customer.first_name %>
  </p>
</div>

<div class="row">
  <p class="col-lg-4 col-md-6 col-sm-4 text-right">フリガナ</p>
  <p class="col-lg-1 col-md-1 col-sm-1">：</p>
  <p class="col-lg-7 col-md-12 col-sm-7">
    <%= customer.last_name_kana %>
    <%= " " %>
    <%= customer.first_name_kana %>
  </p>
</div>

<div class="row">
  <p class="col-lg-4 col-md-6 col-sm-4 text-right">ニックネーム</p>
  <p class="col-lg-1 col-md-1 col-sm-1">：</p>
  <p class="col-lg-7 col-md-12 col-sm-7">
    <%= customer.nickname %>
  </p>
</div>

<div class="row">
  <p class="col-lg-4 col-md-6 col-sm-4 text-right">電話番号</p>
  <p class="col-lg-1 col-md-1 col-sm-1">：</p>
  <p class="col-lg-7 col-md-12 col-sm-7">
    <%= customer.phone_number %>
  </p>
</div>

<div class="row">
  <p class="col-lg-4 col-md-6 col-sm-4 text-right">年齢</p>
  <p class="col-lg-1 col-md-1 col-sm-1">：</p>
  <p class="col-lg-7 col-md-3 col-sm-7">
    <%= customer.age %>
  </p>
</div>

app/views/admin/customers/edit.html.erb
<h2 class="mt-3">
  会員詳細情報 / ステータス編集
</h2>

<%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, class:"mt-3" do |f| %>
  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label "名前" %>
    </div>

    <div class="row col-lg-3 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.last_name %></p>
      <p class="ml-3"><%= @customer.first_name %></p>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label "フリガナ" %>
    </div>

    <div class="row col-lg-3 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.last_name_kana %></p>
      <p class="ml-3"><%= @customer.first_name_kana %></p>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label :nickname, "ニックネーム" %>
    </div>

    <div class="row col-lg-6 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.nickname %></p>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label :phone_number, "電話番号（ハイフンなし）" %>
    </div>

    <div class="row col-lg-6 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.phone_number %></p>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label :age, "年齢" %>
    </div>

    <div class="row col-lg-6 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.age %></p>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label :email, "メールアドレス" %>
    </div>

    <div class="row col-lg-6 col-md-7 col-sm-7">
      <p class="ml-3"><%= @customer.email %></p>
    </div>
  </div>

  <div class="row field form-group">
    <p class="col-lg-3 col-md-4 col-sm-5 text-right">
      投稿数：
      <%= @customer.posts.count %>
    </p>

    <p class="ml-3">
      レビュー数：<%= @customer.reviews.count %>
    </p>
  </div>

  <div class="row field form-group">
    <p class="col-lg-3 col-md-4 col-sm-5 text-right">登録年/日</p>

    <p class="col-lg-6 col-md-7 col-sm-7"><%= @customer.created_at.strftime("%Y/%m/%d") %></p>
  </div>

  <div class="row field form-group">
    <p class="col-lg-3 col-md-4 col-sm-5 text-right">更新年/日</p>

    <p class="col-lg-6 col-md-7 col-sm-7"><%= @customer.updated_at.strftime("%Y/%m/%d") %></p>
  </div>


  <div class="row field form-group mt-2">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right">
      <%= f.label :"会員ステータス" %>
    </div>

    <div class="form-check">
      <%= f.radio_button :is_deleted, false, required: true, class:"form-check-input" %>
      <%= f.label :is_deleted, "有効" %>
    </div>

    <div class="form-check ml-2">
      <%= f.radio_button :is_deleted, true, required: true, class:"form-check-input" %>
      <%= f.label :is_deleted, "無効" %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-5 text-right offset-1">
      <%= f.submit "編集完了", class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<h2 class="mt-3">会員一覧</h2>

<% if @customers.count >= 1 %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th class="col-lg-4 col-md-4 col-sm-3">ニックネーム</th>
        <th class="col-lg-2 col-md-2 col-sm-2">投稿数</th>
        <th class="col-lg-3 col-md-3 col-sm-3">レビュー数</th>
        <th class="col-lg-3 col-md-3 col-sm-4">会員ステータス</th>
      </tr>
    </thead>

    <% @customers.each do |customer| %>
    <tbody>
      <tr>
        <td>
          <%= link_to admin_customer_path(customer), class:"text-dark" do %>
            <%= customer.nickname.truncate(8, separator: "...") %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_customer_posts_path(customer), class:"text-dark" do %>
            <%= customer.posts.count %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_customer_reviews_path(customer), class:"text-dark" do %>
            <%= customer.reviews.count %>
          <% end %>
        </td>
        <% if customer.is_deleted == false %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-danger">退会</td>
        <% end %>
      </tr>
    </tbody>
    <% end %>
  </table>
<% else %>
  <h5>会員が登録されていません</h5>
<% end %>

app/views/admin/customers/post.html.erb
<div class="row mt-3">
  <h2 class="col-lg-5"><%= @customer.nickname %>さんの投稿一覧</h2>
</div>

<% if @posts.count >= 1 %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-lg-2 col-md-2 col-sm-3">投稿の種類</th>
        <th class="col-lg-3 col-md-4 col-sm-3">タイトル</th>
        <th class="col-lg-2 col-md-2 col-sm-2">分析スコア</th>
        <th class="col-lg-2 col-md-2 col-sm-2">コメント数</th>
        <th class="col-lg-3 col-md-2 col-sm-2">投稿年_日</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td nowrap><%= post.genre.genre %></td>
        <td>
          <%= link_to admin_post_path(post.id), class:"text-dark" do %>
            <%= post.title.truncate(8, separator: "...") %>
          <% end %>
        </td>
        <td>
          <% if post.score != nil %>
            <strong>
            <% if post.score >= 0.4 %>
              <span class="text-success"><%= post.score %></span>
            <% elsif post.score <= -0.4 %>
              <span class="text-danger"><%= post.score %></span>
            <% else %>
              <%= post.score %>
            <% end %>
            </strong>
          <% end %>
        </td>
        <td><%= post.post_comments.count %></td>
        <td><%= post.created_at.strftime("%Y_%m/%d") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5>投稿はありません</h5>
<% end %>

app/views/admin/customers/review.html.erb
<div class="row mt-3">
  <h2 class="col-lg-5"><%= @customer.nickname %>さんのレビュー一覧</h2>
</div>

<% if @reviews.count >= 1 %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-lg-2 col-md-3 col-sm-3">タイトル</th>
        <th class="col-lg-2 col-md-3 col-sm-3">評価</th>
        <th class="col-lg-3 col-md-2 col-sm-2">商品</th>
        <th class="col-lg-2 col-md-2 col-sm-2">コメント数</th>
        <th class="col-lg-2 col-md-2 col-sm-2">投稿年_日</th>
      </tr>
    </thead>

    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td>
            <%= link_to admin_review_path(review.id), class:"text-dark omit" do %>
              <%= review.title.truncate(8, separator: "...") %>
            <% end %>
          </td>
          <td nowrap>
            <%= render 'admin/reviews/star', review: review %>
          </td>
          <td>
            <%= link_to admin_item_path(review.item_id), class:"text-dark" do %>
              <%= image_tag review.item.get_image(50, 50) %>
              <%= review.item.name.truncate(8, separator: "...") %>
            <% end %>
          </td>
          <td><%= review.review_comments.count %></td>
          <td><%= review.updated_at.strftime("%Y_%m/%d") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5>レビューはありません</h5>
<% end %>

app/views/admin/customers/show.html.erb
<h2 class="row col justify-content-center mt-3">
  <%= @customer.nickname %>さんのページ
</h2>

<div class="row mt-4">
  <div class="col-lg-5 col-md-5 p-3">
    <div class="border border-dark">
      <h5 class="text-center mt-2">会員情報</h5>

      <%= render 'show', customer: @customer %>

      <div class="row">
        <p class="col-lg-4 col-md-6 col-sm-4 text-right">投稿数</p>
        <p class="col-lg-1 col-md-1 col-sm-1">：</p>
        <%= link_to admin_customer_posts_path(@customer), class:"text-dark" do %>
          <p class="col-lg-7 col-md-3 col-sm-7">
            <%= @customer.posts.count %>
          </p>
        <% end %>
      </div>

      <div class="row">
        <p class="col-lg-4 col-md-6 col-sm-4 text-right">レビュー数</p>
        <p class="col-lg-1 col-md-1 col-sm-1">：</p>
        <%= link_to admin_customer_reviews_path(@customer), class:"text-dark" do %>
          <p class="col-lg-7 col-md-3 col-sm-7">
            <%= @customer.reviews.count %>
          </p>
        <% end %>
      </div>

      <div class="row">
        <p class="col-lg-4 col-md-5 col-sm-4 text-right">ステータス</p>
        <p class="col-lg-1 col-md-1 col-sm-1">：</p>
        <% if @customer.is_deleted == false %>
          <p class="col-lg-7 col-md-3 col-sm-7 text-success">有効</p>
        <% else %>
          <p class="col-lg-7 col-md-3 col-sm-7 text-danger">無効</p>
        <% end %>
      </div>

      <div class="row">
        <p class="col-lg-4 col-md-5 col-sm-5 text-right">登録年/日</p>
        <p class="col-lg-1 col-md-1 col-sm-1">：</p>
        <p class="col-lg-7 col-md-4 col-sm-6"><%= @customer.created_at.strftime("%Y/%m/%d") %></p>
      </div>

      <div class="row">
        <p class="col-lg-4 col-md-5 col-sm-5 text-right">更新年/日</p>
        <p class="col-lg-1 col-md-1 col-sm-1">：</p>
        <p class="col-lg-7 col-md-4 col-sm-6"><%= @customer.updated_at.strftime("%Y/%m/%d") %></p>
      </div>

      <div class="col text-center">
        <%= link_to "情報の確認 / 編集", edit_admin_customer_path(@customer.id), class:"btn btn-primary mb-3" %>
      </div>
    </div>
  </div>

  <div class="row col-lg-6 col-md-6 ml-3">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <% if @posts.first != nil %>
        <div class="row">
          <h5 class="col-lg-5 col-md-12">最新の投稿</h5>

          <%= link_to admin_customer_posts_path(@customer), class:"col-lg-7 col-md-12" do %>
            <p class="btn btn-outline-info btn-sm text-dark">この会員の投稿一覧へ</p>
          <% end %>
        </div>

        <div class="col card p-2">
          <h6 class="card-title">
            <%= link_to admin_post_path(@posts.first), class:"text-dark" do %>
              <strong><%= @posts.first.title %></strong>
            <% end %>
          </h6>

          <p class="card-text">
            <%= @posts.first.text %>
          </p>
        </div>

        <p class="col mt-2 text-right">
          投稿日時
          <%= @posts.first.created_at.strftime("%Y_%m/%d_%H:%M") %>
        </p>
      <% else %>
        <h5 class="col mt-3">投稿はありません</h5>
      <% end %>
    </div>

    <div class="col-lg-12 col-md-12">
      <% if @reviews.first != nil %>
        <div class="row">
          <h5 class="col-lg-5 col-md-12">最新のレビュー</h5>

          <%= link_to admin_customer_reviews_path(@customer),class:"col-lg-7 col-md-12" do %>
            <p class="btn btn-outline-info btn-sm text-dark">この会員のレビュー一覧へ</p>
          <% end %>
        </div>

        <div class="col card p-2">
          <h6 class="card-title">
            <%= link_to admin_review_path(@reviews.first), class:"text-dark" do %>
              <strong><%= @reviews.first.title %></strong>
            <% end %>
          </h6>

          <h6 class="card-subtitle">
            商品名：<%= @reviews.first.item.name %>
          </h6>

          <%= render 'admin/reviews/star', review: @reviews.first %>

          <p class="card-text mt-2">
            <%= @reviews.first.text %>
          </p>
        </div>

        <p class="col mt-2 text-right">
          投稿日時
          <%= @reviews.first.updated_at.strftime("%Y_%m/%d_%H:%M") %>
        </p>
      <% else %>
        <h5 class="col mt-3">レビューはありません</h5>
      <% end %>
    </div>
  </div>
</div>