config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about", as: "about"
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :items
    #itemsに対してreviewsをネストしないのはレビュー一覧で全てのレビュー情報を表示するため
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews do
      resources :review_comments
    end
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :genres
    get "item/confirm/:id" => "items#confirm", as: "item/confirm"
    resources :items
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts
    resources :post_comments
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews
    resources :review_comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :last_name, presence: true, length: { in: 1..50 }
  validates :first_name, presence: true, length: { in: 1..50 }
  validates :last_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :first_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :nickname, presence: true, length: { in: 1..15 }
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120, message: "は0から120までが登録できます" }

  def self.guest
    find_or_create_by!(nickname: 'ゲスト会員' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.first_name = 'ゲスト'
      customer.first_name_kana = '会員'
      customer.last_name = 'ゲスト'
      customer.last_name_kana = 'カイイン'
      customer.nickname = 'ゲスト会員'
      customer.phone_number = 00012344321
      customer.age = 20
      customer.is_deleted = false
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy

  validates :genre, presence: true, length: { in: 1..15 }

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :review, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, length: { in: 1..50 }
  validates :introduction, presence: true, length: { in: 1..255 }
  validates :price, presence: true, numericality: {only_integer: true}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  belongs_to :genre
  has_many :post_comments, dependent: :destroy

  validates :title, presence: :true, length: { in: 1..20 }
  validates :text, presence: :true, length: { in: 1..255 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :customer
  belongs_to :post

  validates :comment, presence: :true, length: { in: 1..255 }

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  has_many :review_comments, dependent: :destroy

  validates :evaluation, presence: true
  validates :title, presence: :true, length: { in: 1..20 }
  validates :text, presence: true, length: { in: 1..255 }

end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :comment, presence: true, length: { in: 1..255 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      @genre = Genre.new
      render :index
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:genre)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def index
    @items = Item.all.order('updated_at DESC')
  end

  def show
    @item = Item.find(params[:id])
    @reviews = Review.where(item_id: @item.id).order('updated_at DESC')
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  def confirm
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def confirm
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    customer_id = @post.customer_id
    @post.destroy
    redirect_to admin_customer_path(customer_id)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @reviews = Review.all.order('updated_at DESC')
  end

  def show
    @review = Review.find(params[:id])
  end

  def confirm
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    customer_id = @review.customer_id
    @review.destroy
    redirect_to admin_customer_path(customer_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :nickname, :phone_number, :age])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/review_helper.rb
module Admin::ReviewHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/reviews/_review_card.html.erb
<div class="col card">
  <div class="row">
    <div class="col-lg-11 col-md-11 col-sm-11 card-title ml-2 p-2">
      <strong><%= review.title %></strong>
    </div>

    <div class="row col-lg-11 col-md-11 col-sm-11 text-right ml-2">
      <%= render 'admin/reviews/star', review: review %>
    </div>
  </div>

  <div class="card-text p-2">
    <p class="p-1"><%= review.text %></p>
  </div>
</div>

<p class="col-lg-12 col-md-12 col-sm-12 text-right mt-3">
  投稿日時
  <%= review.updated_at.strftime("%Y_%m/%d_%H:%M") %>
</p>

app/views/admin/reviews/_review_confirm.html.erb
<div class="card mt-2">
  <h6 class="card-title p-1">
    タイトル：<strong><%= review.title %></strong>
  </h6>

  <div class="row p-1">
    <p class="ml-3">評価：</p>
    <%= render 'admin/reviews/star', review: review %>
  </div>

  <div class="card-text p-2"><strong>内容</strong>
    <p class="p-1"><%= review.text %></p>
  </div>
</div>

<p class="col text-right mt-3">
  投稿日時
  <%= review.updated_at.strftime("%Y_%m/%d_%H:%M") %>
</p>

app/views/admin/reviews/_review_thead.html.erb
<thead>
  <tr>
    <th class="col-lg-2 col-md-2 col-sm-2">タイトル</th>
    <th class="col-lg-2 col-md-3 col-sm-2">評価</th>
    <th class="col-lg-3 col-md-2 col-sm-2">商品</th>
    <th class="col-lg-2 col-md-2 col-sm-3">投稿者</th>
    <th class="col-lg-2 col-md-2 col-sm-2">コメント数</th>
    <th class="col-lg-1 col-md-1 col-sm-1">投稿年_日</th>
  </tr>
</thead>

app/views/admin/reviews/_star.html.erb
<%# ★評価を表示するための記述 %>
<div id="star<%= review.id %>"></div>
<script>
  $('#star<%= review.id %>').empty();
  $('#star<%= review.id %>').raty({
    size: 36,
    starOff: '<%= asset_path('star-off.png') %>',
    starOn: '<%= asset_path('star-on.png') %>',
    half: false,
    readOnly: true,
    score:<%= review.evaluation %>
  });
</script>

app/views/admin/reviews/confirm.html.erb
<h2 class="text-danger text-center mt-3">
  <strong>レビュー削除確認</strong>
</h2>

<div class="row">
  <div class="col-lg-5 col-md-5 col-sm-12 mb-3">
    <h5 class="col text-center mt-2">
      投稿者：<strong><%= @review.customer.nickname %></strong>
    </h5>

    <%= render 'review_confirm', review: @review %>

    <p class="row justify-content-center text-center mt-3">
      <strong>
        このレビューに関連する情報が完全に消去されます<br />
        本当に削除してもよろしいですか？
      </strong>
    </p>

    <div class="col text-center">
      <%= link_to "削除する", admin_review_path(@review.id), method: :delete, class:"btn btn-outline-danger" %>
      <p class="mt-2">削除すると投稿者のページに移動します</p>
    </div>
  </div>

  <div class="col-lg-6 col-md-6 col-sm-12 ml-2">
    <h5 class="text-center">
      コメント件数：<%= @review.review_comments.count %>
    </h5>

    <% if @review.review_comments.count >= 1 %>
      <% @review.review_comments.each do |review_comment| %>
        <%= render 'admin/posts/confirm_comment', comment: review_comment %>
      <% end %>
    <% else %>
      <p class="text-center">このレビューに対するコメントはありません</p>
    <% end %>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class="row mt-3">
  <h2 class="col-lg-5 col-md-5 col-sm-5">レビュー一覧</h2>

  <p class="col-lg-5 col-md-5 col-sm-6 ml-3"><%= link_to "レビューコメント一覧へ", admin_review_comments_path, class:"btn btn-info" %></p>
</div>

<% if @reviews.count >= 1 %>
  <table class="table">
    <%= render 'review_thead' %>
    
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td>
            <%= link_to admin_review_path(review.id), class:"text-dark" do %>
              <%= review.title.truncate(8, separator: "...") %>
            <% end %>
          </td>
          <td nowrap>
            <%= render 'star', review: review %>
          </td>
          <td>
            <%= link_to admin_item_path(review.item_id), class:"text-dark" do %>
              <%= image_tag review.item.get_image(50, 50) %>
              <%= review.item.name.truncate(8, separator: "...") %>
            <% end %>
          </td>
          <td>
            <%= link_to admin_customer_path(review.customer_id), class:"text-dark" do %>
              <%= review.customer.nickname.truncate(8, separator: "...") %>
            <% end %>
          </td>
          <td><%= review.review_comments.count %></td>
          <td><%= review.updated_at.strftime("%Y_%m/%d") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>レビューはありません</h4>
<% end %>

app/views/admin/reviews/show.html.erb
<h2 class="mt-3">レビュー詳細</h2>

<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-12 mb-3">
    <div class="card">
      <%= image_tag @review.item.get_image(200, 200), class:"card-img-top" %>

      <div class="p-2">
        <p><%= @review.item.name %></p>
        <p>価格：<%= @review.item.price %>円</p>
        <p><%= @review.item.introduction %></p>
      </div>
    </div>
  </div>

  <div class="col-lg-7 col-md-7 col-sm-11 ml-2">
    <h5 class="col text-center mt-2">
      投稿者：
      <%= link_to admin_customer_path(@review.customer.id), class:"text-dark" do %>
        <strong><%= @review.customer.nickname %></strong>
      <% end %>
    </h5>

    <%= render 'review_card', review: @review %>

    <div class="col-lg-12 col-md-12 col-sm-12 text-center mt-4">
      <%= link_to "削除画面へ", admin_review_confirm_path(@review.id), class:"btn btn-danger" %>
    </div>

    <div class="mt-5">
      <h5 class="text-center">
        コメント件数：<%= @review.review_comments.count %>
      </h5>

      <% if @review.review_comments.count >= 1 %>
        <% @review.review_comments.each do |review_comment| %>
          <div class="card col mt-4">
            <div class="row card-title border-bottom">
              <%= render 'admin/posts/show_comment', comment: review_comment %>

              <%= link_to "コメント削除", admin_review_comment_path(review_comment.id), method: :delete, class:"btn btn-outline-danger col","data-confirm" => "このコメントを削除しますか？" %>
            </div>

            <p class="card-tect p-1"><%= review_comment.comment %></p>
          </div>
        <% end %>
      <% else %>
        <p class="text-center">このレビューに対するコメントはありません</p>
      <% end %>
    </div>
  </div>
</div>