config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about", as: "about"
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :items
    #itemsに対してreviewsをネストしないのはレビュー一覧で全てのレビュー情報を表示するため
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews do
      resources :review_comments
    end
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts do
      resources :post_comments
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "customers/:id/reviews" => "customers#review", as: "customer/reviews"
    get "customers/:id/posts" => "customers#post", as: "customer/posts"
    resources :customers
    resources :genres
    get "item/confirm/:id" => "items#confirm", as: "item/confirm"
    resources :items
    get "post/confirm/:id" => "posts#confirm", as: "post/confirm"
    resources :posts
    resources :post_comments
    get "review/confirm/:id" => "reviews#confirm", as: "review/confirm"
    resources :reviews
    resources :review_comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :last_name, presence: true, length: { in: 1..50 }
  validates :first_name, presence: true, length: { in: 1..50 }
  validates :last_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :first_name_kana, presence: true, length: { in: 1..50 }, format: { with: /\p{katakana}/ }
  validates :nickname, presence: true, length: { in: 1..15 }
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120, message: "は0から120までが登録できます" }

  def self.guest
    find_or_create_by!(nickname: 'ゲスト会員' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.first_name = 'ゲスト'
      customer.first_name_kana = '会員'
      customer.last_name = 'ゲスト'
      customer.last_name_kana = 'カイイン'
      customer.nickname = 'ゲスト会員'
      customer.phone_number = 00012344321
      customer.age = 20
      customer.is_deleted = false
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy

  validates :genre, presence: true, length: { in: 1..15 }

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :review, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, length: { in: 1..50 }
  validates :introduction, presence: true, length: { in: 1..255 }
  validates :price, presence: true, numericality: {only_integer: true}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  belongs_to :genre
  has_many :post_comments, dependent: :destroy

  validates :title, presence: :true, length: { in: 1..20 }
  validates :text, presence: :true, length: { in: 1..255 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :customer
  belongs_to :post

  validates :comment, presence: :true, length: { in: 1..255 }

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  has_many :review_comments, dependent: :destroy

  validates :evaluation, presence: true
  validates :title, presence: :true, length: { in: 1..20 }
  validates :text, presence: true, length: { in: 1..255 }

end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :comment, presence: true, length: { in: 1..255 }

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def index
    @items = Item.all.order('updated_at DESC')
  end

  def show
    @item = Item.find(params[:id])
    @reviews = Review.where(item_id: @item.id).order('updated_at DESC')
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  def confirm
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def confirm
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    customer_id = @post.customer_id
    @post.destroy
    redirect_to admin_customer_path(customer_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :nickname, :phone_number, :age])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/review_helper.rb
module Admin::ReviewHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin.html.erb
<ul class="navbar-nav">
  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "商品一覧", admin_items_path, class:"btn btn-secondary" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "会員一覧", admin_customers_path, class:"btn btn-secondary" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "投稿一覧", admin_posts_path, class:"btn btn-secondary" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "レビュー一覧", admin_reviews_path, class:"btn btn-secondary" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-secondary" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-secondary" %>
  </li>

</ul>

app/views/layouts/_customer.html.erb
<ul class="navbar-nav m-auto">
  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "商品一覧", items_path, class:"btn btn-warning" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "会員一覧", customers_path, class:"btn btn-warning" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "投稿一覧", posts_path, class:"btn btn-warning" %>
  </li>

  <li class="nav-item text-right pl-2 pt-2">
    <%= link_to "レビュー一覧", reviews_path, class:"btn btn-warning" %>
  </li>

  <%# 会員がログインしているかで表示を切り替える %>
  <% if customer_signed_in? %>
    <li class="nav-item text-right pl-2 pt-2">
      <%= link_to "マイページ", customer_path(current_customer.id), class:"btn btn-warning" %>
    </li>

    <li class="nav-item text-right pl-2 pt-2">
      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-warning" %>
    </li>
  <% else %>
    <li class="nav-item text-right pl-2 pt-2">
      <%= link_to "about", about_path, class:"btn btn-warning" %>
    </li>

    <li class="nav-item text-right pl-2 pt-2">
      <%= link_to "ログイン", customer_session_path, class:"btn btn-warning" %>
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ふかふかパン</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <%= image_tag('logo.png') %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <!--ログインしているアカウントによってheaderを変える-->
            <% if admin_signed_in? %>
            <!--adminアカウントログイン時のheader-->
              <%= render '/layouts/admin' %>
            <% else %>
            <!--ログイン前とcustomerアカウントでのログイン時-->
              <%= render '/layouts/customer' %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container mb-4">
        <%= yield %>
      </div>
    </main>

    <footer></footer>
  </body>
</html>